### ISSUE TITLE
Patchouli book extension fails

### ISSUE THREAD

**Issue by JustinHuPrime** [Talia-12/Hexal#50]
Minecraft version: 1.19.2
Hexal version: 0.2.14
Hexcasting version: 0.10.3

Upon loading a world, Patchouli logs an error of "Error loading extending book hexcasting:thehexbook with addon book hexal:hexalbook, skipping"

The hex notebook is indeed missing any sort of mention of Hexal items

**Comment by JustinHuPrime** [comment]
This appears to be a regression in 0.2.14 - using 0.2.13 works just fine

**Comment by LlamaSageR** [comment]
Successfully recreated this bug. The specific issue is that the Interop category used by the Fabric-Only patterns does not actually exist with just Hexal. Adding Pehkui fixed the Patchouli error and the Hexal entries reappeared.

From what I can gather, Hex Casting only enables that category if Gravity Changer API or Pehkui is installed via [HexInterop.java](https://github.com/gamma-delta/HexMod/blob/eade2a52067d5bbda86a9d5e37adf5ca5f862e4b/Common/src/main/java/at/petrak/hexcasting/interop/HexInterop.java), and since Hexal isn't accounted for, attempting to add the Fabric-Only section to this nonexistent category breaks it.

> PatchouliAPI.get().setConfigFlag(PATCHOULI_ANY_INTEROP_FLAG, anyInterop);

This is the specific line responsible for setting the category, so somehow setting this to true would fix the issue.
I lack the experience with code to actually write/implement this, or else I'd try to do it myself. Perhaps something like this would work, after checking somewhere if Fabric is enabled?

> PatchouliAPI.get().setConfigFlag("hexcasting:any_interop", true);

**Comment by Talia-12** [comment]
Alright, this should be fixed for the next version.
